// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return web;
      case TargetPlatform.iOS:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE0zvBCdhP2rKk6xsbnYojxIkvR9Lsqg8',
    appId: '1:820865249110:web:43bcd7146cf2ac2239f0f7',
    messagingSenderId: '820865249110',
    projectId: 'coders-hub-cdf3d',
    authDomain: 'coders-hub-cdf3d.firebaseapp.com',
    storageBucket: 'coders-hub-cdf3d.firebasestorage.app',
    measurementId: 'G-5328QB4M99',
  );
}
